apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exam-resource-role-binding
  namespace: exam
subjects:
  - kind: User
    name: tahirrida # Remplacez par le nom de votre utilisateur
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: exam-resource-role
  apiGroup: rbac.authorization.k8s.io
